name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: [ '3.1.x', '6.0.x' ]
    name: .NET ${{ matrix.dotnet }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./AIS --no-restore
    - name: Test
      run: dotnet test ./AIS --no-build --verbosity normal
